[package]
name = "the-rust-programming-language"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
rand = { version = "0.8.5", features = ["std_rng"] }
rand_pcg = "0.3.1"
rand_seeder = "0.3.0"
